### ISSUE TITLE
What is the first model here? $model_{alien + human}$

### ISSUE THREAD

**Issue by startakovsky** [eth-sri/language-model-arithmetic#1]
Hi, I am curious what this first model in the table from your paper is -- I don't see this model listed in the appendix... image below 

Thanks...

<img width="546" alt="image" src="https://github.com/eth-sri/language-model-arithmetic/assets/689723/a77b82a1-a3aa-4c24-93f7-7ec16918fbf1">

**Comment by startakovsky** [comment]
The only thing I might _guess_ is that the prompt was "You are an alien and you are a human" 🤷

**Comment by JasperDekoninck** [comment]
Thanks for catching this! We indeed went for a rather simple prompt: "You are an alien and a human."
We note that you can find the code for all our examples in the [`scripts/examples.py`](https://github.com/eth-sri/language-model-arithmetic/blob/main/scripts/examples.py) file. 
We will update the appendix in our next update of the Arxiv paper :)
