### ISSUE TITLE
Max_length and Max_new_tokens

### ISSUE THREAD

**Issue by Yuancheng-Xu** [eth-sri/language-model-arithmetic#8]
Hello,

I notice that in the readme (https://github.com/eth-sri/language-model-arithmetic?tab=readme-ov-file#integrating-classifiers), you use `print(ma.generate_text("Write a one-sentence fairy tale.", max_length=128))`. However, according to https://github.com/eth-sri/language-model-arithmetic/blob/26d367c16dab1a6943e877c06c263b1c8125a860/src/model_arithmetic/model_arithmetic.py#L741

It seems that the generate_text function does not use a "max_length" arguments. Did you mean max_new_tokens?

If that is the case, I am wondering how to set "max_length" during generation. By convention, "max_length" refers to the total length of input and output, and "max_new_tokens" refers to the length of output only.

Thanks!

**Comment by JasperDekoninck** [comment]
Hi! 

Thanks for pointing this out! I changed the parameter in the code to `max_new_tokens` to be more like the standard names of the parameters, but forgot to update it in the README. I updated the README to change this now :)
